name: Update Dash Core download links

on:
  repository_dispatch:
    types: [release_published]
  workflow_dispatch:  # This allows the workflow to be triggered manually
  schedule: # Run daily at midnight and noon UTC
    - cron: 0 0,12 * * *

jobs:
  update-core-download-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Run core download link update script
      id: update_script
      run: |
        output=$("${GITHUB_WORKSPACE}/scripts/core-download-link-update.sh")
        # Extract the version number from the line that starts with "Extracted Version:"
        version=$(echo "$output" | grep "Extracted Version:" | awk -F": " '{print $2}')
        echo "version=${version}" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: update-docs/core-update-${{ github.sha }}
        title: "chore: update core download links to version ${{ steps.update_script.outputs.version }}"
        body: |
          This PR updates download links in the documentation to use Dash Core version ${{ steps.update_script.outputs.version }}.
        commit-message: "chore: update core download links to version ${{ steps.update_script.outputs.version }}"
        reviewers: "thephez,PastaPastaPasta,UdjinM6"
